### ISSUE TITLE
Trying to get this to run on my mac

### ISSUE THREAD

**Issue by johnnonolan** [botriot/faceup#2]
but I'm getting a ('The connection is not writable'); 
when i make a requst from the server. 

I'm probably doing something stupid.Any ideas?

**Comment by johnnonolan** [comment]
hmm upgrading node from 0.4.x to 0.6.11has got me further. 

```
The "sys" module is now called "util". It should have a similar interface.
```

actually that's not the error when request / from server i get a 

`    Express server listening on port 3000 in development mode
overlay: jason image: http://faceup.me/image/casey.jpeg
overlay: hipster image: http://faceup.me/image/derek.png
overlay: clown image: http://faceup.me/image/jon.jpg
overlay: scumbag image: http://faceup.me/image/wade.jpeg
overlay: clown image: http://faceup.me/image/tom-hanks.jpg

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: write EPIPE
    at errnoException (net.js:646:11)
    at Object.afterWrite [as oncomplete](net.js:480:18)
`
